### PR TITLE
Cleanup of an unsuccessful merge in gitignore

### PR DESCRIPTION
**Pull request by MrCsabaToth**
I removed the R.java, since that will be in the gen folder, so should be ignored anyway. Removed the image too, looked weird there.

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Pull request #29 by Connor Brooks is more elegant

**Comment by jguomoto** [comment]
LGTM on the changes

**Comment by MrCsabaToth** [comment]
#29 looked better

**Comment by jguomoto** [comment]
@MrCsabaToth I am confirming that at the moment, I will have it merged when the CLA is ready :) ..

**Pull request merged**
